name: Project Deploy Flow
on: 
  push:
    branches:
      - 'master'
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build-Image
        run: docker build -t sheason/www.sheason.fun .
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Image
        run: docker push sheason/www.sheason.fun
  Deploy:
    needs: [Build-Image]
    name: Deploy Docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            # 进入工作区
            cd /root/www
            # 使用Docker compose启动服务
            docker compose up -d